In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('survey lung cancer.csv')

In [3]:
dataset

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,M,69,1,2,2,1,1,2,1,2,2,2,2,2,2,YES
1,M,74,2,1,1,1,2,2,2,1,1,1,2,2,2,YES
2,F,59,1,1,1,2,1,2,1,2,1,2,2,1,2,NO
3,M,63,2,2,2,1,1,1,1,1,2,1,1,2,2,NO
4,F,63,1,2,1,1,1,1,1,2,1,2,2,1,1,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,F,56,1,1,1,2,2,2,1,1,2,2,2,2,1,YES
305,M,70,2,1,1,1,1,2,2,2,2,2,2,1,2,YES
306,M,58,2,1,1,1,1,1,2,2,2,2,1,1,2,YES
307,M,67,2,1,2,1,1,2,2,1,2,2,2,1,2,YES
308,M,62,1,1,1,2,1,2,2,2,2,1,1,2,1,YES

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 309 entries, 0 to 308
Data columns (total 16 columns):
GENDER                   309 non-null object
AGE                      309 non-null int64
SMOKING                  309 non-null int64
YELLOW_FINGERS           309 non-null int64
ANXIETY                  309 non-null int64
PEER_PRESSURE            309 non-null int64
CHRONIC DISEASE          309 non-null int64
FATIGUE                  309 non-null int64
ALLERGY                  309 non-null int64
WHEEZING                 309 non-null int64
ALCOHOL CONSUMING        309 non-null int64
COUGHING                 309 non-null int64
SHORTNESS OF BREATH      309 non-null int64
SWALLOWING DIFFICULTY    309 non-null int64
CHEST PAIN               309 non-null int64
LUNG_CANCER              309 non-null object
dtypes: int64(14), object(2)
memory usage: 38.8+ KB

In [5]:
dataset.columns.tolist()

['GENDER',
 'AGE',
 'SMOKING',
 'YELLOW_FINGERS',
 'ANXIETY',
 'PEER_PRESSURE',
 'CHRONIC DISEASE',
 'FATIGUE ',
 'ALLERGY ',
 'WHEEZING',
 'ALCOHOL CONSUMING',
 'COUGHING',
 'SHORTNESS OF BREATH',
 'SWALLOWING DIFFICULTY',
 'CHEST PAIN',
 'LUNG_CANCER']

In [7]:
dataset.columns=dataset.columns.str.lower()

In [8]:
dataset['lung_cancer'].replace({'YES':2,'NO':1},inplace=True)
dataset[['lung_cancer']]

     lung_cancer
0              2
1              2
2              1
3              1
4              1
..           ...
304            2
305            2
306            2
307            2
308            2

[309 rows x 1 columns]

In [9]:
dataset['gender'].replace({'M':1,'F':0},inplace=True)
dataset[['gender']]

     gender
0         1
1         1
2         0
3         1
4         0
..      ...
304       0
305       1
306       1
307       1
308       1

[309 rows x 1 columns]

In [10]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 309 entries, 0 to 308
Data columns (total 16 columns):
gender                   309 non-null int64
age                      309 non-null int64
smoking                  309 non-null int64
yellow_fingers           309 non-null int64
anxiety                  309 non-null int64
peer_pressure            309 non-null int64
chronic disease          309 non-null int64
fatigue                  309 non-null int64
allergy                  309 non-null int64
wheezing                 309 non-null int64
alcohol consuming        309 non-null int64
coughing                 309 non-null int64
shortness of breath      309 non-null int64
swallowing difficulty    309 non-null int64
chest pain               309 non-null int64
lung_cancer              309 non-null int64
dtypes: int64(16)
memory usage: 38.8 KB